### ISSUE TITLE
Manual install fails with class not loadable / not found

### ISSUE THREAD

**Issue by murphy83** [harrigo/EverCrumbs#1]
Just tried to use this plugin and got the following error:
```
[11-Jun-2018 07:46:15 UTC] PHP Fatal error:  Uncaught Error: Class 'Harrigo\EverCrumbs\Block\Evercrumbs' not found in /services/http/vhost/shop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
Stack trace:
#0 /services/http/vhost/shop/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Harrigo\\EverCru...', Array)
#1 /services/http/vhost/shop/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Harrigo\\EverCru...', Array)
#2 /services/http/vhost/shop/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Harrigo\\EverCru...', Array)
#3 /services/http/vhost/shop/vendor/magento/framework/View/Layout/Generator/Block.php(257): Magento\Framework\View\Element\BlockFactory->createBlock('Harrigo\\EverCru...', Array)
#4 /services/http/vhost/shop/vendor/magento/framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\L in /services/http/vhost/shop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111
```

How I tried to install:
- clone current release from github
- copy all Files into the folder app/code/Harrigo/EverCrumbs letting the structure intact
- no errors reported on setup:di:compile or setup:upgrade
- cache was flushed

Did I miss anything?

**Comment by harrigo** [comment]
Ok sorry about that and the long wait I had a look and tested and it seems fine for me. I had a seperate issue for it than you however and have fixed that the other day. Can you try it again for me and let me know how it goes?
